# Nome da aplicação
spring.application.name=agendamento

# Configuração Dinâmica do Banco de Dados
# Quando estiver na nuvem (Render), ele pega a URL, usuário e senha do servidor.
# Quando estiver no seu PC, ele usa o banco H2 em memória.
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${JDBC_DATABASE_USERNAME:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${JDBC_DATABASE_DRIVER:org.h2.Driver}

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Permite acessar o console do H2 localmente se necessário
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
